### PR TITLE
finished

### PR DESCRIPTION
**Pull request by Cdunlow**
i very much enjoyed  this week.

### CODE REVIEW

**Comment by halfaro1** [comment]
@Cdunlow great work just make sure the exception error message matches exactly what I wrote in the instructions.

**Comment by Cdunlow** [comment]
I don't understand why you think its not written like what you wrote? i copy and pasted the sentence.

**Comment by halfaro1** [comment]
@Cdunlow the spacing doesn't match, and the automated test will not pass unless it's an exact match.

**Comment by halfaro1** [comment]
@Cdunlow 
Thanks for continuing to work on this project! Unfortunately, I have to grade this project as-is. I am closing out this pull request and entering your grade on Blackboard. Please see your grade there.

**Pull request closed without merging**
